### PR TITLE
Changed timeslot to HH instead of H/h

### PR DESCRIPTION
**Pull request by dpldevelopers**

### CODE REVIEW

**Comment by trotzig** [comment]
Hi @dpldevelopers, thanks for the PR! Would you mind explaining why you want to make this change? It's easier for me to review if I know the reasoning behind the change. Thanks!

**Comment by dpldevelopers** [comment]
@trotzig I changed time format to accommodate leading zero for ISO 8601 standard.

**Comment by trotzig** [comment]
Sounds good! There's a failing test (test/AvailableTimes-test.jsx) that you need to update to get the tests to pass.

**Comment by dpldevelopers** [comment]
@trotzig Done

**Comment by trotzig** [comment]
Thanks!

**Comment by trotzig** [comment]
Released in https://github.com/trotzig/react-available-times/releases/tag/v1.3.0

**Pull request merged**
